// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCdF-70EfGH6fFJIA1l6yJEJeG6C2XrtRk',
    appId: '1:919329399276:web:d15afe6e6003e8bb7da0c9',
    messagingSenderId: '919329399276',
    projectId: 'plan-genie-hackathon',
    authDomain: 'plan-genie-hackathon.firebaseapp.com',
    storageBucket: 'plan-genie-hackathon.firebasestorage.app',
    measurementId: 'G-GGYEZS3H9N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGSfTXQNTCEE_rBFmNWNt7soJyB4E10Dg',
    appId: '1:919329399276:android:40d62c5d23a523837da0c9',
    messagingSenderId: '919329399276',
    projectId: 'plan-genie-hackathon',
    storageBucket: 'plan-genie-hackathon.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyClaMu7tCL_4scHaqttXxzattvzAPJpY6Y',
    appId: '1:919329399276:ios:81936eb4b7359d8d7da0c9',
    messagingSenderId: '919329399276',
    projectId: 'plan-genie-hackathon',
    storageBucket: 'plan-genie-hackathon.firebasestorage.app',
    iosBundleId: 'com.plangenie.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyClaMu7tCL_4scHaqttXxzattvzAPJpY6Y',
    appId: '1:919329399276:ios:81936eb4b7359d8d7da0c9',
    messagingSenderId: '919329399276',
    projectId: 'plan-genie-hackathon',
    storageBucket: 'plan-genie-hackathon.firebasestorage.app',
    iosBundleId: 'com.plangenie.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCdF-70EfGH6fFJIA1l6yJEJeG6C2XrtRk',
    appId: '1:919329399276:web:9dda4ece4de323ad7da0c9',
    messagingSenderId: '919329399276',
    projectId: 'plan-genie-hackathon',
    authDomain: 'plan-genie-hackathon.firebaseapp.com',
    storageBucket: 'plan-genie-hackathon.firebasestorage.app',
    measurementId: 'G-RFBLJLJ2DX',
  );
}
