name: plangenie
description: Flutter client for the PlanGenie travel planning experience.
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  google_fonts: ^6.2.1
  firebase_core: ^4.1.0
  firebase_auth: ^6.0.2
  google_sign_in: ^7.2.0
  flutter_riverpod: ^2.5.1
  http: ^1.2.1
  shared_preferences: ^2.2.2
  flutter_svg: ^2.0.10+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  # Add custom fonts by listing them here once available.
